@PJConsulting_WebAPI_HostAddress = http://localhost:5200

GET {{PJConsulting_WebAPI_HostAddress}}/service
Accept: application/json

###

GET {{PJConsulting_WebAPI_HostAddress}}/service/1
Accept: application/json

###

POST {{PJConsulting_WebAPI_HostAddress}}/service
Content-Type: application/json

{
  "id": 1,
  "name": "Example Service",
  "description": "A description of the service"
}

###

PUT {{PJConsulting_WebAPI_HostAddress}}/service/1
Content-Type: application/json

{
  "id": 1,
  "name": "Updated Service",
  "description": "An updated description"
}

###

DELETE {{PJConsulting_WebAPI_HostAddress}}/service/1

###
